blueprint:
  name: Bambu Lab Zigbee RGB Controller
  description: Control one or more RGB lights with Bambu 3d printer
  domain: automation
  input:
    printer_status:
      name: Print Status of your Bambu Lab printer
      description: Select the print status entity.
      selector:
        entity:
          filter:
          - domain:
            - sensor
            integration: bambu_lab
          multiple: false
    current_stage:
      name: Current Stage of your Bambu Lab Printer
      description: Select the printer current stage entity.
      selector:
        entity:
          filter:
          - domain:
            - sensor
            integration: bambu_lab
          multiple: false
    printer_state:
      name: Printer state On/Off of your Bambu Lab Printer
      description: Select the printer state binary sensor.
      selector:
        entity:
          filter:
          - domain:
            - binary_sensor
            integration: bambu_lab
          multiple: false
    zha_lights:
      name: RGB Light devices
      description: Select the RGB light devices you wish to control.
      selector:
        device:
          filter:
          - integration: zha
          multiple: true
  source_url: https://gist.github.com/dreed47/b33a76472cc813f7bf48a63c3dde7dce
alias: Bambu Lab RGB Controller
description: ''
trigger:
- platform: state
  entity_id:
  - !input printer_state
  - !input printer_status
  - !input current_stage
  alias: When printer stage,status or state changes
condition: []
action:
- delay:
    hours: 0
    minutes: 0
    seconds: 5
    milliseconds: 0
- if:
  - condition: state
    state: 'on'
    alias: printer state is on
    entity_id: !input printer_state
  - condition: not
    conditions:
    - condition: state
      entity_id: !input printer_stage
      state: scanning_bed_surface
      alias: scanning Bed Surface
    - condition: state
      entity_id: !input printer_stage
      state: cleaning_nozzle_tip
      alias: cleaning Nozzle Tip
    - condition: state
      entity_id: !input printer_stage
      state: calibrating_extrusion
      alias: calibrating Extrusion
    - condition: state
      entity_id: !input printer_status
      state: offline
      alias: Printer is off
    alias: And Lidar is NOT on
  then:
  - service: light.turn_on
    data:
      rgb_color:
      - 255
      - 255
      - 255
      brightness_pct: 100
      effect: Freqmatrix
    alias: Turn RGB light on white with effect
    target:
      device_id: !input zha_lights
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: !input printer_stage
          state: paused_filament_runout
        - condition: state
          entity_id: !input printer_stage
          state: paused_front_cover_falling
        - condition: state
          entity_id: !input printer_stage
          state: paused_nozzle_temperature_malfunction
        - condition: state
          entity_id: !input printer_stage
          state: paused_heat_bed_temperature_malfunction
        - condition: state
          entity_id: !input printer_stage
          state: paused_chamber_temperature_control_error
        - condition: state
          entity_id: !input printer_stage
          state: paused_cutter_error
        - condition: state
          entity_id: !input printer_stage
          state: paused_first_layer_error
      sequence:
      - service: light.turn_on
        data:
          rgb_color:
          - 255
          - 0
          - 0
          brightness: 255
          effect: Blink
        target:
          device_id: !input zha_lights
        alias: Turn on RGB to red
    alias: Do we need to set color to red?
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: !input printer_stage
          state: idle
      sequence:
      - service: light.turn_on
        data:
          rgb_color:
          - 255
          - 0
          - 195
          brightness: 200
          effect: Oscillate
        target:
          device_id: !input zha_lights
        alias: Turn on RGB to fushia with oscillate effect
    alias: Do we need to set color to white?
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: !input printer_stage
          state: printing
      sequence:
      - service: light.turn_on
        data:
          rgb_color:
          - 255
          - 255
          - 255
          brightness: 255
          effect: Solid
        target:
          device_id: !input zha_lights
        alias: Turn on RGB to full white while printing
    alias: Do we need to set color to white?
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: !input printer_stage
          state: filament_unloading
        - condition: state
          entity_id: !input printer_stage
          state: filament_loading
      sequence:
      - service: light.turn_on
        data:
          rgb_color:
          - 255
          - 255
          - 255
          brightness: 255
          effect: Solid
        target:
          device_id: !input zha_lights
        alias: Turn on RGB to white to check if loading/unloading is ok
    alias: Do we need to set color to white?
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: !input printer_status
          state: finish
      sequence:
      - service: light.turn_on
        data:
          rgb_color:
          - 0
          - 255
          - 0
          brightness: 255
          effect: Solid
        target:
          device_id: !input zha_lights
        alias: Turn on RGB to green
    alias: Do we need to set color to green?
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: !input printer_status
          state: pause
      sequence:
      - service: light.turn_on
        data:
          rgb_color:
          - 0
          - 255
          - 0
          brightness: 255
          effect: Blink
        target:
          device_id: !input zha_lights
        alias: Turn on RGB to green with blink effect
    alias: Do we need to set color to green?
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: !input printer_stage
          state: auto_bed_leveling
      sequence:
      - service: light.turn_on
        data:
          rgb_color:
          - 0
          - 0
          - 255
          brightness: 255
          effect: Blink
        target:
          device_id: !input zha_lights
        alias: Turn on RGB to blue
    alias: Do we need to set color to blue?
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: !input printer_stage
          state: heatbed_preheating
        - condition: state
          entity_id: !input printer_stage
          state: Heating Hotend
      sequence:
      - service: light.turn_on
        data:
          rgb_color:
          - 255
          - 169
          - 0
          brightness: 255
          effect: Blink
        target:
          device_id: !input zha_lights
        alias: Turn on RGB to yellow
    alias: Do we need to set color to yellow?
  else:
    - if:
      - condition: state
        state: 'idle'
        alias: printer state is idle for 15 sec
        entity_id: !input current_stage
      then:
      - delay: "00:00:15"
      - if:
        - condition: state
          state: 'idle'
          entity_id: !input current_stage
          for:
            hours: 0
            minutes: 0
            seconds: 10
        then:
        - service: light.turn_off
          data: {}
          target:
            device_id: !input zha_lights
          alias: Turn RGB light off
mode: single







